title: Iniciación en R para científicos
author: Miguel Rojas

theme: minima

linkedin: "https://www.linkedin.com/in/itsmiguelrojas/"
github: "https://github.com/itsmiguelrojas/"
kaggle: "https://www.kaggle.com/itsmiguelrojas/"
instagram: "https://www.instagram.com/itsmiguelrojas/"
