title: "Iniciación en R para científicos"
author: "Miguel Rojas"
description: "© Copyright, Miguel Rojas. 2022"

theme: minima

google_analytics: G-53Q7TS10C0

linkedin: "https://www.linkedin.com/in/itsmiguelrojas/"
github: "https://github.com/itsmiguelrojas/"
kaggle: "https://www.kaggle.com/itsmiguelrojas/"
instagram: "https://www.instagram.com/itsmiguelrojas/"
